### ISSUE TITLE
Update Bundle for Akeneo 3.0

### ISSUE THREAD

**Issue by amansilla** [flagbit/akeneo-table-attribute-bundle#12]
Akeneo 3.0 was released and for being able to use this bundle for the newest version, it needs to be tested and updated in case of breaks.

https://www.akeneo.com/release-notes/

**Comment by newQuery** [comment]
That'd be great indeed!

**Comment by franckcharpentier** [comment]
I tried to install the module on version 3 of Akeneo.

`composer require "flagbit/table-attribute-bundle":"3.0.x-dev"`

ok

But `php bin/console cache:clear` returned :

> In BaseNode.php line 319:
> Invalid configuration for path "akeneo_storage_utils.mapping_overrides.0.original": Invalid original class ""Pim\\Bundle\\CatalogBundle\\Entity\\AttributeOption"".

So in app/config/config.yml I have replaced

```
akeneo_storage_utils:
    mapping_overrides:
        -
            original: Pim\Bundle\CatalogBundle\Entity\AttributeOption
            override: Flagbit\Bundle\TableAttributeBundle\Entity\AttributeOption
```

By

```
akeneo_storage_utils:
    mapping_overrides:
        -
            original: Akeneo\Pim\Structure\Component\Model\AttributeOption
            override: Flagbit\Bundle\TableAttributeBundle\Entity\AttributeOption
```

But `php bin/console cache:clear` still returns :

> In ParameterBag.php line 102:
> The service "flagbit_table.array_converter.flat_to_standard.product.value_converter.text" has a dependency on a non-existent parameter "pim_connector.array_converter.flat_to_standard.product.value_converter.text.class".
