### ISSUE TITLE
labels seems not to be installed

### ISSUE THREAD

**Issue by IngolfWagner** [flagbit/akeneo-table-attribute-bundle#51]

**Comment by IngolfWagner** [comment]
I installed your plugin following your description on the readme : 

```
<?php
// config/bundles.php
return [
    // ...
    Flagbit\Bundle\TableAttributeBundle\FlagbitTableAttributeBundle::class => ['all' => true],
];
```
```
# config/packages/table.yml
akeneo_storage_utils:
    mapping_overrides:
        -   original: Akeneo\Pim\Structure\Component\Model\AttributeOption
            override: Flagbit\Bundle\TableAttributeBundle\Entity\AttributeOption
```
Than I ran the following commands
```
php bin/console --env=prod cache:clear
php bin/console --env=prod doctrine:schema:update --force
NO_DOCKER=true make cache assets css javascript-prod
```

Because also tried on a test instance the 2 other doctrine commands, but they seem to just create errors, so I didn't roll them out here.

The plugin seems to work, but labels and icons are missing:
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/66115479/93209887-08370a00-f75f-11ea-95f8-02ee0805f50f.png)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/66115479/93209896-0b31fa80-f75f-11ea-8432-2a14fd52138b.png)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/66115479/93209898-0bca9100-f75f-11ea-9e40-af054ad6c36d.png)


My system setup is : 
![image](https://user-images.githubusercontent.com/66115479/93209954-1dac3400-f75f-11ea-8090-1ec90ffeb2cd.png)
